version: "2"
services:
    zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"
        networks:
            - tc-network
    kafka:
        image: wurstmeister/kafka:2.11-1.1.1
        ports:
            - "9092:9092"
        networks:
            - tc-network
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
            KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    api:
        build: services/api
        ports:
            - "3000:3000"
        networks:
            - tc-network
    website:
        build: services/website
        ports:
            - "5173:3000"
        networks:
            - tc-network
networks:
    tc-network:
        driver: bridge
